# Generated by Django 4.0.3 on 2024-04-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
