# Generated by Django 4.0.3 on 2024-04-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
