# Generated by Django 4.0.3 on 2024-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
