# Generated by Django 4.0.3 on 2024-04-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_course_certificate_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_title',
        ),
    ]
