# Generated by Django 4.0.3 on 2024-04-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_calender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_zone', models.TextField(default='Asia/Kolkata')),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.certificate')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
