# Generated by Django 4.0.3 on 2024-04-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_training_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='training_calender',
            name='delivery',
            field=models.CharField(max_length=255),
        ),
    ]
