# Generated by Django 4.0.3 on 2024-04-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_trainingcalendar_delete_training_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcalendar',
            name='time_zone',
            field=models.CharField(default='Asia/Kolkata', max_length=255),
        ),
    ]
