# Generated by Django 4.0.3 on 2024-04-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_trainingcalendar_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcalendar',
            name='certificate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_calendars', to='account.certificate'),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='course_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_calendars', to='account.course'),
        ),
    ]
