# Generated by Django 4.0.3 on 2024-04-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_trainingcalendar_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcalendar',
            name='course_fk',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course/images'),
        ),
        migrations.AddField(
            model_name='trainingcalendar',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='MRP',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.certificate'),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
