# Generated by Django 4.0.3 on 2024-04-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_trainingcalendar_course_fk_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcalendar',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
    ]
