# Generated by Django 4.0.3 on 2024-04-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_trainingcalendar_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
