# Generated by Django 4.0.3 on 2024-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMPDeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('list', models.JSONField()),
                ('timeliness', models.CharField(max_length=200)),
                ('view', models.CharField(max_length=200)),
            ],
        ),
    ]
