# Generated by Django 4.0.3 on 2024-04-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_pmpdeliverymethod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PMPDeliveryMethod',
            new_name='testmodel',
        ),
    ]
