# Generated by Django 4.0.3 on 2024-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_rename_enterprise_solutions_testmodel_delivery_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='steps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
