# Generated by Django 4.0.3 on 2024-04-28 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_testmodel_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='heading',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='certificate',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='account.certificate'),
        ),
    ]
