# Generated by Django 4.0.3 on 2024-04-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_testmodel_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.certificate'),
        ),
    ]
