# Generated by Django 4.0.3 on 2024-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_trainingcalendar_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
