# Generated by Django 4.0.3 on 2024-05-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='know_more_title',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='learning_overview_desc',
        ),
    ]
