# Generated by Django 4.0.3 on 2024-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_testmodel_know_more_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
